// <auto-generated />
using System;
using Curiosity.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Curiosity.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513154802_AddRocketsTable")]
    partial class AddRocketsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Curiosity.Api.Entities.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Agencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Description = "National Aeronautics and Space Administration.",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg",
                            Name = "NASA"
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            Description = "Space Exploration Technologies Corp.",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/d/de/SpaceX-Logo.svg",
                            Name = "SpaceX"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Europe",
                            Description = "European Space Agency.",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/6/6e/ESA_logo_simple.svg",
                            Name = "ESA"
                        },
                        new
                        {
                            Id = 4,
                            Country = "China",
                            Description = "China National Space Administration.",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/b/b2/Insignia_of_CNSA.svg",
                            Name = "CNSA"
                        },
                        new
                        {
                            Id = 5,
                            Country = "India",
                            Description = "Indian Space Research Organisation.",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/b/bd/Indian_Space_Research_Organisation_Logo.svg",
                            Name = "ISRO"
                        });
                });

            modelBuilder.Entity("Curiosity.Api.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "5463f82b-1b4e-4e42-9e8a-e990c79f977c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "74ebb7b8-97b7-4457-a552-8905da06c8fd",
                            CreatedAt = new DateTime(2026, 5, 13, 15, 48, 1, 672, DateTimeKind.Utc).AddTicks(8847),
                            Email = "admin@curiosity.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Administrator",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@CURIOSITY.COM",
                            NormalizedUserName = "ADMIN@CURIOSITY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHBXNtku5WJemgyt8O8GK2KOkuiejjU6goDSu+ZgIe1tzAkWy8RoMpj6yJZlu07lUA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin@curiosity.com"
                        });
                });

            modelBuilder.Entity("Curiosity.Api.Entities.Launch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FlightStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LaunchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LaunchLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LiveStreamUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<int>("RocketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("RocketId");

                    b.ToTable("Launches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlightStatus = "Scheduled",
                            IsFeatured = false,
                            LaunchDate = new DateTime(2026, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchLocation = "Kourou, French Guiana",
                            MissionId = 1,
                            RocketId = 6
                        },
                        new
                        {
                            Id = 2,
                            FlightStatus = "Scheduled",
                            IsFeatured = true,
                            LaunchDate = new DateTime(2026, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchLocation = "Kennedy Space Center, FL",
                            MissionId = 2,
                            RocketId = 2
                        },
                        new
                        {
                            Id = 3,
                            FlightStatus = "Scheduled",
                            IsFeatured = false,
                            LaunchDate = new DateTime(2027, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchLocation = "Kourou, French Guiana",
                            MissionId = 3,
                            RocketId = 4
                        },
                        new
                        {
                            Id = 4,
                            FlightStatus = "Scheduled",
                            IsFeatured = false,
                            LaunchDate = new DateTime(2027, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchLocation = "Wenchang, China",
                            MissionId = 4,
                            RocketId = 7
                        },
                        new
                        {
                            Id = 5,
                            FlightStatus = "Scheduled",
                            IsFeatured = false,
                            LaunchDate = new DateTime(2026, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchLocation = "Kennedy Space Center, FL",
                            MissionId = 5,
                            RocketId = 3
                        },
                        new
                        {
                            Id = 6,
                            FlightStatus = "Scheduled",
                            IsFeatured = false,
                            LaunchDate = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchLocation = "Kennedy Space Center / Starbase",
                            MissionId = 6,
                            RocketId = 5
                        },
                        new
                        {
                            Id = 7,
                            FlightStatus = "Scheduled",
                            IsFeatured = false,
                            LaunchDate = new DateTime(2027, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchLocation = "Kennedy Space Center, FL",
                            MissionId = 7,
                            RocketId = 2
                        },
                        new
                        {
                            Id = 8,
                            FlightStatus = "Scheduled",
                            IsFeatured = false,
                            LaunchDate = new DateTime(2028, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchLocation = "Kennedy Space Center, FL",
                            MissionId = 8,
                            RocketId = 3
                        },
                        new
                        {
                            Id = 9,
                            FlightStatus = "Scheduled",
                            IsFeatured = false,
                            LaunchDate = new DateTime(2028, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchLocation = "TBA",
                            MissionId = 9,
                            RocketId = 1
                        },
                        new
                        {
                            Id = 10,
                            FlightStatus = "Scheduled",
                            IsFeatured = false,
                            LaunchDate = new DateTime(2035, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchLocation = "Kourou, French Guiana",
                            MissionId = 10,
                            RocketId = 4
                        },
                        new
                        {
                            Id = 11,
                            FlightStatus = "Success",
                            IsFeatured = false,
                            LaunchDate = new DateTime(1969, 7, 16, 13, 32, 0, 0, DateTimeKind.Unspecified),
                            LaunchLocation = "Kennedy Space Center, FL",
                            MissionId = 11,
                            RocketId = 8
                        },
                        new
                        {
                            Id = 12,
                            FlightStatus = "Success",
                            IsFeatured = false,
                            LaunchDate = new DateTime(1977, 9, 5, 12, 56, 0, 0, DateTimeKind.Unspecified),
                            LaunchLocation = "Cape Canaveral, FL",
                            MissionId = 12,
                            RocketId = 9
                        },
                        new
                        {
                            Id = 13,
                            FlightStatus = "Success",
                            IsFeatured = false,
                            LaunchDate = new DateTime(2012, 10, 8, 0, 35, 0, 0, DateTimeKind.Unspecified),
                            LaunchLocation = "Cape Canaveral, FL",
                            MissionId = 13,
                            RocketId = 1
                        });
                });

            modelBuilder.Entity("Curiosity.Api.Entities.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewsArticleBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayloadDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.ToTable("Missions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgencyId = 1,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/2/2a/JWST_spacecraft_model_3.png",
                            NewsArticleBody = "The James Webb Space Telescope (JWST) is a space telescope designed primarily to conduct infrared astronomy.",
                            PayloadDescription = "Infrared astronomy mission to explore the early universe.",
                            Title = "James Webb Space Telescope"
                        },
                        new
                        {
                            Id = 2,
                            AgencyId = 1,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/5/59/Europa_Clipper_spacecraft_model.png",
                            NewsArticleBody = "Europa Clipper will perform dozens of close flybys of Jupiter's moon Europa.",
                            PayloadDescription = "Studying the Galilean moon Europa to investigate its habitability.",
                            Title = "Europa Clipper"
                        },
                        new
                        {
                            Id = 3,
                            AgencyId = 3,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/3/3d/Juice_launch_kit_cover_close-up.png",
                            NewsArticleBody = "JUICE will spend at least three years making detailed observations of Jupiter.",
                            PayloadDescription = "Jupiter Icy Moons Explorer studying Ganymede, Callisto, and Europa.",
                            Title = "JUICE"
                        },
                        new
                        {
                            Id = 4,
                            AgencyId = 4,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/c/cb/Chang%27e_6_lunar_samples_at_IAC_2024_01.jpg",
                            NewsArticleBody = "The mission aims to collect samples from the South Pole-Aitken basin.",
                            PayloadDescription = "Lunar sample return mission from the far side of the Moon.",
                            Title = "Chang'e 6"
                        },
                        new
                        {
                            Id = 5,
                            AgencyId = 1,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/1/15/Earthset_%28art002e009288%29.jpg",
                            NewsArticleBody = "Artemis II is the first planned crewed mission of NASA's Artemis program.",
                            PayloadDescription = "First crewed mission of the Artemis program to orbit the Moon.",
                            Title = "Artemis II"
                        },
                        new
                        {
                            Id = 6,
                            AgencyId = 1,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/1/19/Artemis_III_ESM3_Engine_Nozzle_Install_Completion_%28KSC-20260217-PH-JBS01_0002%29.jpg",
                            NewsArticleBody = "Artemis III will be the first human mission to the lunar South Pole.",
                            PayloadDescription = "Human return to the lunar surface.",
                            Title = "Artemis III"
                        },
                        new
                        {
                            Id = 7,
                            AgencyId = 1,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/3/3c/Lunar_Gateway_rendering_2.webp",
                            NewsArticleBody = "Gateway will serve as a multi-purpose outpost orbiting the Moon.",
                            PayloadDescription = "A lunar space station.",
                            Title = "Lunar Gateway"
                        },
                        new
                        {
                            Id = 8,
                            AgencyId = 1,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/0/07/Mars_sample_returnjpl.jpg",
                            NewsArticleBody = "MSR will collect and return Martian samples for the first time.",
                            PayloadDescription = "Bringing Mars rocks to Earth.",
                            Title = "Mars Sample Return"
                        },
                        new
                        {
                            Id = 9,
                            AgencyId = 1,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/f/f7/Dragonfly_render_June_2025.png",
                            NewsArticleBody = "Dragonfly will explore the chemistry of Saturn's moon Titan.",
                            PayloadDescription = "Rotorcraft to explore Titan.",
                            Title = "Dragonfly"
                        },
                        new
                        {
                            Id = 10,
                            AgencyId = 3,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/f/f5/LISA-waves.jpg",
                            NewsArticleBody = "LISA will detect gravitational waves from space.",
                            PayloadDescription = "Gravitational wave observatory.",
                            Title = "LISA"
                        },
                        new
                        {
                            Id = 11,
                            AgencyId = 1,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/9/98/Apollo_11_Lunar_Module_Eagle_in_lunar_orbit_viewed_from_Command_Module_Columbia.jpg",
                            NewsArticleBody = "Apollo 11 was the first spaceflight that landed humans on the Moon.",
                            PayloadDescription = "First crewed lunar landing.",
                            Title = "Apollo 11"
                        },
                        new
                        {
                            Id = 12,
                            AgencyId = 1,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/d/d2/Voyager.jpg",
                            NewsArticleBody = "Voyager 1 is a space probe launched by NASA in 1977.",
                            PayloadDescription = "Interstellar mission to the outer solar system.",
                            Title = "Voyager 1"
                        },
                        new
                        {
                            Id = 13,
                            AgencyId = 2,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/2/2a/Falcon_9_launching_CRS-1.jpg",
                            NewsArticleBody = "CRS-1 was the first commercial resupply mission to the International Space Station.",
                            PayloadDescription = "First commercial resupply mission to the ISS.",
                            Title = "SpaceX CRS-1"
                        });
                });

            modelBuilder.Entity("Curiosity.Api.Entities.Rocket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PayloadCapacity")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Rockets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Reusable two-stage rocket.",
                            Manufacturer = "SpaceX",
                            Name = "Falcon 9",
                            PayloadCapacity = 22800.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Most powerful operational rocket.",
                            Manufacturer = "SpaceX",
                            Name = "Falcon Heavy",
                            PayloadCapacity = 63800.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Space Launch System for Artemis.",
                            Manufacturer = "Boeing/NASA",
                            Name = "SLS Block 1",
                            PayloadCapacity = 95000.0
                        },
                        new
                        {
                            Id = 4,
                            Description = "European heavy-lift launch vehicle.",
                            Manufacturer = "ArianeGroup",
                            Name = "Ariane 6",
                            PayloadCapacity = 21600.0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Fully reusable transport system.",
                            Manufacturer = "SpaceX",
                            Name = "Starship",
                            PayloadCapacity = 100000.0
                        },
                        new
                        {
                            Id = 6,
                            Manufacturer = "ArianeGroup",
                            Name = "Ariane 5",
                            PayloadCapacity = 21000.0
                        },
                        new
                        {
                            Id = 7,
                            Manufacturer = "CALT",
                            Name = "Long March 5",
                            PayloadCapacity = 25000.0
                        },
                        new
                        {
                            Id = 8,
                            Manufacturer = "Boeing/North American/Douglas",
                            Name = "Saturn V",
                            PayloadCapacity = 140000.0
                        },
                        new
                        {
                            Id = 9,
                            Manufacturer = "Martin Marietta",
                            Name = "Titan IIIE",
                            PayloadCapacity = 15400.0
                        });
                });

            modelBuilder.Entity("Curiosity.Api.Entities.UserFavoriteMission", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "MissionId");

                    b.HasIndex("MissionId");

                    b.ToTable("UserFavoriteMissions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            ConcurrencyStamp = "9954dc7c-df35-4c91-8f86-906af7fa0651",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            ConcurrencyStamp = "fbb9a360-c2dd-4e16-b2f1-934c8f708de0",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "5463f82b-1b4e-4e42-9e8a-e990c79f977c",
                            RoleId = "8e445865-a24d-4543-a6c6-9443d048cdb9"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Curiosity.Api.Entities.Launch", b =>
                {
                    b.HasOne("Curiosity.Api.Entities.Mission", "Mission")
                        .WithMany("Launches")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Curiosity.Api.Entities.Rocket", "Rocket")
                        .WithMany("Launches")
                        .HasForeignKey("RocketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Rocket");
                });

            modelBuilder.Entity("Curiosity.Api.Entities.Mission", b =>
                {
                    b.HasOne("Curiosity.Api.Entities.Agency", "Agency")
                        .WithMany("Missions")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("Curiosity.Api.Entities.UserFavoriteMission", b =>
                {
                    b.HasOne("Curiosity.Api.Entities.Mission", "Mission")
                        .WithMany("FavoritedByUsers")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Curiosity.Api.Entities.ApplicationUser", "User")
                        .WithMany("FavoriteMissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Curiosity.Api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Curiosity.Api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Curiosity.Api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Curiosity.Api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Curiosity.Api.Entities.Agency", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("Curiosity.Api.Entities.ApplicationUser", b =>
                {
                    b.Navigation("FavoriteMissions");
                });

            modelBuilder.Entity("Curiosity.Api.Entities.Mission", b =>
                {
                    b.Navigation("FavoritedByUsers");

                    b.Navigation("Launches");
                });

            modelBuilder.Entity("Curiosity.Api.Entities.Rocket", b =>
                {
                    b.Navigation("Launches");
                });
#pragma warning restore 612, 618
        }
    }
}
